services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    ports:
      - 8191:8191
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/New_York
    restart: unless-stopped
    networks:
      - media
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    ports:
      - 9696:9696
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/prowlarr:/config
    restart: unless-stopped
    networks:
      - media
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    profiles:
      - radarr
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/radarr:/config
    #      - /mnt/riven/mount/movies:/movies
    restart: unless-stopped
    networks:
      - media
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    profiles:
      - sonarr
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/sonarr:/config
    #      - /mnt/riven/mount/tv:/tv
    restart: unless-stopped
    networks:
      - media
  lidarr:
    image: linuxserver/lidarr:develop
    container_name: lidarr
    profiles:
      - linarr
    ports:
      - 8686:8686
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/lidarr:/config
    #      - /mnt/riven/mount/music:/music
    restart: unless-stopped
    networks:
      - media
  whisparr:
    image: ghcr.io/hotio/whisparr:nightly
    container_name: whisparr
    profiles:
      - whisparr
    ports:
      - 10300:6969
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/whisparr:/config
    #      - /mnt/riven/mount/adult:/adult
    restart: unless-stopped
    networks:
      - media
  overseerr:
    image: linuxserver/overseerr:latest
    container_name: overseerr
    ports:
      - 5055:5055
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/overseerr:/config
    restart: unless-stopped
    networks:
      - media
networks:
  media:
    external: true
